### ISSUE TITLE
Default values for Resource Limit and Resource Request

### ISSUE THREAD

**Issue by mstein11** [viadee/docker-hub-rate-limit-exporter#14]
Currently the default values for the limits and requests of the docker-hub-rate-limit-exporter deployment are quite generous, especially for the cpu. 

https://github.com/viadee/docker-hub-rate-limit-exporter/blob/0c77941a36b4259a936cdf3084bc66f1685a7bd0/chart/values.yaml#L56-L62 

I think it would be a good idea to lower the defaults for cpu. In our cluster it seems that a request of 50 milli cores and a limit of 100 milli cores seems to be sufficient. 

Can anybody confirm that those values are sufficient for their cluster?

@TJM @shpwrck

**Comment by TJM** [comment]
@mstein11 for sure yes. It uses 19M of memory and doesn't even show up on the CPU usage, but the stats say ~ 0.01 (1%)

I am not sure if I would drop it to 50m, but based on actual usage it looks like it would work fine.

**Comment by mstein11** [comment]
@TJM Thanks for sharing the usage data! What value would you recommend for the cpu request?

**Comment by TJM** [comment]
@mstein11 I would say, _again based on our usage_ (presumably others can check their grafana to corroborate)

```
resources:
    limits:
        cpu: 100m
        memory: 32Mi
    requests:
        cpu: 50m
        memory: 16Mi
```

**Comment by TJM** [comment]
OK, lets not set them that low, it causes cpu throttling, even though it *never* reaches that threshold (which I think is a known bug).
![Screen Shot 2021-02-10 at 9 24 08 AM](https://user-images.githubusercontent.com/1641316/107539157-eca32480-6b81-11eb-8d86-bba454654cd3.png)

**Comment by TJM** [comment]
Testing these numbers:
```
resources:
    limits:
        cpu: 200m
        memory: 32Mi
    requests:
        cpu: 50m
        memory: 20Mi
```

* Even though the CPU limit was ~10x the usage, it was being throttled, so I bumped it up more, this may be a cluster specific (kernel version) problem.
* Upped the memory request to 20M as it seems to stay real steady at 18-19Mi usage

**Comment by mstein11** [comment]
Thanks for testing!

We run with these values:

```
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 50m
        memory: 128Mi
```

resulting in the resource consumption statistic as below: 

<img width="1591" alt="Bildschirmfoto 2021-02-10 um 18 06 41" src="https://user-images.githubusercontent.com/10419286/107545069-25b3b700-6bcb-11eb-8631-b0bc1becae61.png">
<img width="1577" alt="Bildschirmfoto 2021-02-10 um 18 07 30" src="https://user-images.githubusercontent.com/10419286/107545098-2c422e80-6bcb-11eb-88c6-4bd520eb3d49.png">

Since our memory consumption is a bit higher I would suggest the following defaults:

```
resources:
    limits:
        cpu: 200m
        memory: 96Mi
    requests:
        cpu: 50m
        memory: 64Mi
```

WDYT?

**Comment by TJM** [comment]
Interesting, your CPU usage is in line with what I am seeing, but tour memory is significantly higher (double)... I wonder if I am running an old version? :-/

**Comment by TJM** [comment]
We are seeing a *tiny* bit of throttling at 200m limit. Less than 1%. Acceptable for me ... 25% might cause a warning alert :)


![Screen Shot 2021-02-10 at 10 39 57 AM](https://user-images.githubusercontent.com/1641316/107548976-85d73880-6b8c-11eb-980c-b98119f5c1d9.png)

**Comment by mstein11** [comment]
@TJM, I don't think the higher memory consumption is because of an old version. There haven't been any changes in the near past on the code. Maybe the difference in memory consumption is caused by a different docker host / kubernetes version? 

Anyway, I don't think it is a big issue and I think the following values should be fine as defaults:

```
resources:
    limits:
        cpu: 200m
        memory: 96Mi
    requests:
        cpu: 50m
        memory: 64Mi
```
