### ISSUE TITLE
Decrease default resource request and limits in values.yaml

### ISSUE THREAD

**Issue by mstein11** [viadee/docker-hub-rate-limit-exporter#17]
As discussed in #14, the default resource requests and limits currently used are too high. Better values would be the following:

```
resources:
    limits:
        cpu: 200m
        memory: 96Mi
    requests:
        cpu: 50m
        memory: 64Mi 
```
